<<<<<<< HEAD
# Uncomment to enable HDR support
# source=/etc/hyprland/hdr.conf

$defaultMonitor = DP-2
=======
$defaultMonitor = DP-3
>>>>>>> 0a2ee02 (stuff before the purge)

env = DEFAULT_MONITOR,$defaultMonitor

# https://wiki.hyprland.org/Configuring/Monitors/
<<<<<<< HEAD
# monitor=DP-1, preferred, auto, 1
=======
monitor=DP-3, 3840x2160@144, 0x0, 1.5, vrr,1, bitdepth,10
>>>>>>> 0a2ee02 (stuff before the purge)

# https://wiki.hyprland.org/Configuring/Keywords/#executing
exec-once = xrandr --output $defaultMonitor --primary

# https://wiki.hyprland.org/Configuring/Variables/#cursor
cursor {
    default_monitor = $defaultMonitor;
}
