notARepository: "skip"
git:
  overrideGpg: true
customCommands:
  - key: "M"
    command: "git mergetool \"$(git rev-parse --show-toplevel)/{{.SelectedFile.Name}}\""
    context: "files"
    loadingText: "opening git mergetool"
