[Unit]
Name = "komorebi"
Description = "A tiling window manager for Windows"

[Service]
#Autostart = true # Started by masir

[Service.ExecStart]
Executable = "komorebi.exe"
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]

[[Service.ExecStop]]
Executable = "komorebic.exe"
Arguments = ["stop"]

[[Service.ExecStopPost]]
Executable = "komorebic.exe"
Arguments = ["restore-windows"]

[Service.Healthcheck.Command]
Executable = "komorebic.exe"
Arguments = ["state"]
DelaySec = 1
