[Unit]
Name = "komorebi"
Description = "A tiling window manager for Windows"

[Service]
Autostart = true

[Service.ExecStart]
Executable = "komorebi.exe"
Arguments = [
    "--config",
    "$USERPROFILE/.config/komorebi/komorebi.json",
]
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]

[[Service.ExecStop]]
Executable = "komorebic.exe"
Arguments = ["stop"]

[[Service.ExecStopPost]]
Executable = "komorebic.exe"
Arguments = ["restore-windows"]

[Service.Healthcheck.Command]
Executable = "komorebic.exe"
Arguments = ["state"]
