icons_format = "{icon}"

[theme]
theme = "dracula"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:175) |}"

[[block]]
block = "net"
format = " ^icon_net_down $speed_down.eng(prefix:Ki) ^icon_net_up $speed_up.eng(prefix:Ki) "

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "sound"
max_vol = 150
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
device_kind = "source"
format = " $icon "

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%H:%M:%S') "

[[block]]
block = "time"
interval = 10
format = "  $timestamp.datetime(f:'%a. %m.%d.%Y') "
